service: goodies-client

provider:
  name: aws
  region: ${opt:region, 'eu-central-1'}
  stage: ${opt:stage, 'dev'}
  profile: ${opt:profile, 'default'}

custom:
  github:
    owner: DennisSkoko
    repo: goodies-client
    branch:
      prod: dev

resources:
  Resources:
    DistBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        VersioningConfiguration:
          Status: Enabled
        WebsiteConfiguration:
          ErrorDocument: index.html
          IndexDocument: index.html

    DistBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: DistBucket
        PolicyDocument:
          Statement:
            - Sid: DistBucketPolicy
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource:
                Fn::Join:
                  - ''
                  - - Fn::GetAtt: [DistBucket, Arn]
                    - '/*'

    ArtifactStoreProd:
      Type: AWS::S3::Bucket

    CodePipelineRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - codepipeline.amazonaws.com
              Action:
                - sts:AssumeRole

            - Effect: Allow
              Principal:
                Service:
                  - codebuild.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: AmazonS3FullAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 's3:*'
                  Resource: '*'

          - PolicyName: AWSCodeBuildDeveloperAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - codebuild:StartBuild
                    - codebuild:StopBuild
                    - codebuild:BatchGet*
                    - codebuild:Get*
                  Resource:
                    - Fn::Join:
                      - ':'
                      - - arn:aws:codebuild
                        - Ref: AWS::Region
                        - Ref: AWS::AccountId
                        - project/${self:service}-build

          - PolicyName: CloudWatchLogsFullAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - cloudwatch:getMetricData
                    - cloudwatch:listMetrics
                    - logs:DescribeLogGroups
                    - logs:DescribeDestinations
                    - logs:DescribeLogStreams
                    - logs:DescribeLogGroups
                    - logs:DescribeSubscriptionFilters
                    - logs:PutLogEvents
                    - logs:GetLogEvents
                    - logs:FilterLogEvents
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                  Resource:
                    - arn:aws:logs:*:*:*

    CodeBuild:
      Type: AWS::CodeBuild::Project
      Properties:
        Name: ${self:service}-build
        Artifacts:
          Type: S3
          Location:
            Ref: ArtifactStoreProd
          Name: ${self:service}-build.zip
        Environment:
          Type: LINUX_CONTAINER
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/nodejs:8.11.0
        ServiceRole:
          Fn::GetAtt: [CodePipelineRole, Arn]
        Source:
          Type: S3
          Location:
            Fn::Join:
              - ''
              - - Ref: ArtifactStoreProd
                - /SourceCode
          BuildSpec: |
            version: 0.2
            phases:
              install:
                commands:
                  - npm install -g npm
                  - npm ci
              build:
                commands:
                  - npm run build

    CodePipelineProd:
      Type: AWS::CodePipeline::Pipeline
      Properties:
        ArtifactStore:
          Location:
            Ref: ArtifactStoreProd
          Type: S3
        RoleArn:
          Fn::GetAtt: [CodePipelineRole, Arn]
        Stages:
          - Name: Source
            Actions:
              - Name: Source
                ActionTypeId:
                  Category: Source
                  Owner: ThirdParty
                  Provider: GitHub
                  Version: 1
                Configuration:
                  Owner: ${self:custom.github.owner}
                  Repo: ${self:custom.github.repo}
                  Branch: ${self:custom.github.branch.prod}
                  OAuthToken: ${env:GITHUB_OAUTH_TOKEN, opt:github-oauth-token}
                OutputArtifacts:
                  - Name: SourceCode

          - Name: Build
            Actions:
              - Name: Build
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Version: 1
                  Provider: CodeBuild
                Configuration:
                  ProjectName:
                    Ref: CodeBuild
                InputArtifacts:
                  - Name: SourceCode
                OutputArtifacts:
                  - Name: BuildCode
